---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации на сайте с помощью Github
  - Пользователь должен иметь возможность отключить аккаунт Github от своего профиля
  - Пользователь должен иметь возможность авторизации на сайте с помощью Discord
  - Пользователь дожен иметь возможность отключить аккаунт Discord от своего профиля
  - Пользователь должен иметь возможность изменять имя в своем профиле
  - Пользователь должен иметь возможность видеть написание кода соперника и вывод тестов
  - Пользователь должен иметь возмонжность соревноваться с ботом
  - Пользователь должен иметь возмонжность играть с другом по ссылке
  - Пользователь может создать новую игру с другими пользователями
  - Пользователь должен иметь возможность вступить в бой без регистрации
  - Должна быть возможность менять язык программирования во время решения
  - Пользователь может выбрать язык задания в запущенной игре
  - Пользователь должен иметь возможность остановить игру
  - Пользовательно должен иметь возможность сдаться и завершить игру в любой момент
  - Пользователь может просматривать историю игр
  - Пользователь может создать турнир
  - Пользователь должен иметь возможность отправлять сообщения в общий чат
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен иметь мобbльную версию
  - Сайт должен быть совестим с последними версиями браузеров
implicit:
  - пользователь не может редактировать чужой код
